### ISSUE TITLE
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='******.******.com', port=443): Read timed out. (read timeout=None)

### ISSUE THREAD

**Issue by eduardocerqueira** [eduardocerqueira/linknotfound#3]
connection timeout during scanner

`
2023-01-13:19:04:43,850 INFO     [phase.py:129] 200
	/var/tmp/linknotfound/rhosak-ui-build/sourcemaps/139.9724d8cdad71dd24a325e307bc6a21fc.js.map
2023-01-13:19:04:43,899 INFO     [phase.py:129] 200
	/var/tmp/linknotfound/rhosak-ui-build/sourcemaps/139.9724d8cdad71dd24a325e307bc6a21fc.js.map
Traceback (most recent call last):
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/lib64/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='access.redhat.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ecerquei/git/linknotfound/venv/bin/linknotfound", line 33, in <module>
    sys.exit(load_entry_point('linknotfound', 'console_scripts', 'linknotfound')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/linknotfound/main.py", line 27, in scan
    scanner()
  File "/home/ecerquei/git/linknotfound/linknotfound/phase.py", line 145, in scanner
    runner.scan(filtered_repos)
  File "/home/ecerquei/git/linknotfound/linknotfound/phase.py", line 127, in scan
    rp_doc.status = requests.get(url=rp_doc.url).status_code
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecerquei/git/linknotfound/venv/lib64/python3.11/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='******.********.com', port=443): Read timed out. (read timeout=None)
`

**Comment by eduardocerqueira** [comment]
DONE!
